version: '3.3'
services:
  mysql:
    build: ./environments/development/docker/mysql
    ports:
      - "33063:3306"
    environment:
      MYSQL_ROOT_PASSWORD: simplereviewsystem
      MYSQL_DATABASE: simplereviewsystem
      MYSQL_USER: simplereviewsystem
      MYSQL_PASSWORD: simplereviewsystem

  phpfpm:
    build: ./environments/development/docker/php
    links:
     - mysql
     - redis
    expose:
      - "9000"
    volumes:
     - ./environments/development/docker/php/php.ini:/usr/local/etc/php/php.ini
     - ./:/var/www/html
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 120s
    command: php-fpm

  nginx:
    build: ./environments/development/docker/nginx
    links:
      - phpfpm:phpfpm
    expose:
      - "80"
    volumes:
      - ./environments/development/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    environment:
      VIRTUAL_HOST: simple-review-system.local
    networks:
      default:
        aliases:
          - simple-review-system.local

  mailcatcher:
      image: schickling/mailcatcher
      ports:
       - "1080:1080"

  redis:
    build: ./environments/development/docker/redis
    ports:
      - "63790:6379"
    volumes:
      - ./storage/redis:/data
      - ./environments/development/redis/redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint:
      - redis-server
      - "--appendonly yes"

networks:
  default:
    external:
      name: simple-review-system
